#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dancer_android.Resource", IsApplication=true)]

namespace Dancer_android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnPlay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cycle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Pause = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int progressbar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int random = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int btnMenu = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int btnMode = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btnPlay = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int lyricLine1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int lyricLine2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lyricLine3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int lyricLine4 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int lyricLine5 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int lyricLine6 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int lyricLine7 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int lyricLine8 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int lyricLine9 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int musicTitle = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int playProgress = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int default_lyric = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int music_root_path = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
